# -*- coding: utf-8 -*-
"""Iris_oasis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mI90oA3fFBzAkB5bZZK29EQdloVhnmpX

**IRIS Flower Classification** Problem Statement The Iris flower dataset consists of three species: setosa, versicolor, and virginica. These species can be distinguished based on their measurements.Now imagine that you have the measurements of Iris flowers categorized by their respective species. Your objective is to train a machine learning model that can learn from these measurements and accurately classify the Iris flowers into their respective species.
"""

# Importing the required libraries

import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns

# Loading the dataset

flower=pd.read_csv('Iris.csv')
flower.head()

# Getting information about data
flower.info()

# Getting Describe Data
flower.describe()

flower.columns

# to display number of samples on each class

flower['Species'].value_counts()

#Data Visualization
flower['SepalLengthCm'].hist()

flower['SepalWidthCm'].hist()

flower['PetalLengthCm'].hist()

flower['PetalWidthCm'].hist()

colors=['red','orange','blue']
species=['Iris-setosa','Iris-versicolor','Iris-virginica']

#Data Preprocessing
flower.isnull().sum()

#Define Target Variable (y) and Feature Variables (X)
y = flower['Species']
X = flower.drop(columns=['Id','Species'],axis=1)

print(y)

print(X)

#train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size=0.7, random_state=2529)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

#modeling
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=500)

#Model Evaluation
model.fit(X_train,y_train)

model.intercept_

model.coef_

#modelPrediction
y_pred = model.predict(X_test)

y_pred

#model accuracy
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

accuracy_score(y_test,y_pred)

print(classification_report(y_test,y_pred))